name: CI/CD Pipeline for Blue-Green Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  APP_ENVIRONMENT: weekfiveproject
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECS_CLUSTER: weekfiveproject-Cluster
  ECS_SERVICE: ${{ secrets.AWS_SERVICE }}
  ECS_TASK_FAMILY: weekfiveproject-frontend-task
  CODEDEPLOY_APPLICATION: weekfiveproject-frontend-app
  CODEDEPLOY_DEPLOYMENT_GROUP: weekfiveproject-frontend-dg

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Node.js 22
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build React App
      run: npm run build
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public
    
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ secrets.AWS_REGISTRY }}
        ECR_REPOSITORY: ${{ secrets.AWS_REPO_NAME }}
        IMAGE_TAG: image-uploader-frontend
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        echo "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" > image.txt
    
    - name: Upload image name as artifact
      uses: actions/upload-artifact@v3
      with:
        name: image-artifact
        path: image.txt
  
  register-task-definition:
    name: Register Task Definition
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Download image artifact
      uses: actions/download-artifact@v3
      with:
        name: image-artifact
    
    - name: Read image name
      run: echo "IMAGE=$(cat image.txt)" >> $GITHUB_ENV
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Generate task definition JSON
      run: |
        cat <<EOF > task-definition.json
        {
          "family": "${{ env.ECS_TASK_FAMILY }}",
          "cpu": "256",
          "memory": "512",
          "networkMode": "awsvpc",
          "requiresCompatibilities": ["FARGATE"],
          "taskRoleArn": "arn:aws:iam::904233109505:role/weekfiveproject-ecs-task-role",
          "executionRoleArn": "arn:aws:iam::904233109505:role/weekfiveproject-ecs-task-execution-role",
          "containerDefinitions": [
            {
              "name": "${{ env.APP_ENVIRONMENT }}-frontend-container",
              "image": "${{ env.IMAGE }}",
              "essential": true,
              "portMappings": [
                {
                  "containerPort": 80,
                  "hostPort": 80,
                  "protocol": "tcp"
                }
              ]
            }
          ]
        }
        EOF
    
    - name: Register new task definition
      run: |
        TASK_DEFINITION_ARN=$(aws ecs register-task-definition --cli-input-json file://task-definition.json --query 'taskDefinition.taskDefinitionArn' --output text)
        echo "$TASK_DEFINITION_ARN" > task_definition.txt
    
    - name: Upload task definition ARN as artifact
      uses: actions/upload-artifact@v3
      with:
        name: task-definition-artifact
        path: task_definition.txt
  
  deploy:
    name: Deploy via CodeDeploy
    runs-on: ubuntu-latest
    needs: register-task-definition
    steps:
    - name: Download task definition artifact
      uses: actions/download-artifact@v3
      with:
        name: task-definition-artifact
    
    - name: Read task definition ARN
      run: echo "TASK_DEFINITION_ARN=$(cat task_definition.txt)" >> $GITHUB_ENV
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Generate appspec.json
      run: |
        cat <<EOF > appspec.json
        {
          "version": 0.0,
          "Resources": [
            {
              "TargetService": {
                "Type": "AWS::ECS::Service",
                "Properties": {
                  "TaskDefinition": "${{ env.TASK_DEFINITION_ARN }}",
                  "LoadBalancerInfo": {
                    "ContainerName": "${{ env.APP_ENVIRONMENT }}-frontend-container",
                    "ContainerPort": 80
                  }
                }
              }
            }
          ]
        }
        EOF
    
    - name: Trigger CodeDeploy deployment
      run: |
        DEPLOYMENT_ID=$(aws deploy create-deployment \
          --application-name ${{ env.CODEDEPLOY_APPLICATION }} \
          --deployment-group-name ${{ env.CODEDEPLOY_DEPLOYMENT_GROUP }} \
          --deployment-config-name CodeDeployDefault.ECSAllAtOnce \
          --description "Deployment triggered by GitHub Actions" \
          --revision "{\"revisionType\":\"AppSpecContent\",\"appSpecContent\":{\"content\":\"$(cat appspec.json | jq -c -r @json)\"}}" \
          --query 'deploymentId' --output text)
        echo "Deployment ID: $DEPLOYMENT_ID"
